### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by LuongQuyTan1999** [hnthinh2909/layout-oppo#1]
Hiện tại thì file README của bạn viết chưa được ổn cho lắm, có thể tham khảo các link sau và update lại READ của bạn:
- https://github.com/nhim175/shave-it 
- https://github.com/nhim175/coders-tokyo-cli
- https://github.com/nhim175/coders-tokyo-web

Hướng dẫn viết README chuẩn:
- https://www.makeareadme.com/

**Comment by hnthinh2909** [comment]
Mình cảm ơn,
Do dạo này mình vẫn chưa cân bằng được lịch học nên giờ mới check được mail.
Mình sẽ sửa lại theo như hướng dẫn

Vào Th 4, 22 thg 4, 2020 vào lúc 11:28 luongquytan <
notifications@github.com> đã viết:
